GET http://localhost:3306/CARACTERE

###

GET http://localhost:3003/movies

### 

PUT http://localhost:3306/CARACTERE
Content-Type: application/json

{
    "name": "Vampira", 
    "gender": "FEMALE", 
    "description": "Suga a força vital "
}

###
DELETE  http://localhost:3306/CARACTERE/3

###

GET http://localhost:3306/CARACTERE