
###
GET http://localhost:3306/users


###
GET http://localhost:3306/products


//Busca todas a compras de um determiado usuário
###
GET http://localhost:3306/users/:user_id/purchases

### 
post http://localhost:3306/registerUsers
Content-Type: application/json

{
        "name": "ellen Fontes Batista",
        "email": "ellengmail", 
        "password": "785647889"
}


### 
post http://localhost:3306/registerProdcts
Content-Type: application/json

{
        "name": "rolls royce - Mulsanne",
        "description": "Veiculo de Luxo",
        "price":  "4.900,000,00",
        "image": "image.png"
}

### 
post http://localhost:3306/purchases
Content-Type: application/json

{
      "user_id":1, 
      "product_id":2 , 
      "quantity":3, 
      "total_price": "total_price"
    
}